---
#local setup and openstack instance deployment
- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    #- role: openstack-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance



#common libraries across all nodes
- hosts: all
  user: ubuntu
  sudo: yes
  vars_files:
    - host_vars/nectar.yaml
  vars:
    ansible_ssh_private_key_file: "{{ key1 }}"

  roles:
    - role: common

#couch installation on 3 nodes, 1 master and 2 slaves
- hosts: couchadmin:couchnode
  user: ubuntu
  sudo: yes
  vars_files:
    - host_vars/couch.yaml
  vars:
    ansible_ssh_private_key_file: "{{ key1 }}"

  roles:
    - role: couchdb-common

#couch cluster configuration
- hosts: couchadmin
  user: ubuntu
  sudo: yes
  vars_files:
    - host_vars/couch.yaml
  vars:
    ansible_ssh_private_key_file: "{{ key1 }}"

  roles:
    - role: couchdb-admin

#Run stream harvester on one node
- hosts: couchadmin
  user: ubuntu
  sudo: yes
  tasks:
    - name: running the harvester
      shell: cd /source/twitterHarvester; nohup python streamer.py </dev/null >/dev/null 2>&1 &
      
    

#Run search harvester on 2 nodes
- hosts: couchnode
  user: ubuntu
  sudo: yes
  tasks:
    - name: running the harvester
      shell: cd /source/twitterHarvester; nohup python searcher.py </dev/null >/dev/null 2>&1 &

#Run webserver
- hosts: webserver
  user: ubuntu
  sudo: yes
  roles:
    - role: web-server
