#Common vars
availability_zone: melbourne-qh2-uom
network: qh2-uom

#Volume
volumes:
  - vol_name: demo-vol-1
    vol_size: 10
  - vol_name: demo-vol-2
    vol_size: 10
  - vol_name: demo-vol-3
    vol_size: 10
  - vol_name: demo-vol-4
    vol_size: 10    

#Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couch admin
    description: "open 5984 for couch setup"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0   

#host groups order
host_groups:
  - group: webserver
  - group: couchadmin
  - group: couchnode
  - group: couchnode

#Instances 955a0556-1224-4499-a895-87d54d5cbf32
instance_image:  37788d15-12bd-488c-b15e-903d43eae051
instance_key_name: projectkey
instance_flavor: uom.mse.2c9g

ansible_ssh_private_key_file:  ./projectkey.pem

COUCHDB_PASSWORD: admin