- name: install tweepy
  pip: 
    name: tweepy

- name: install couchdb-python
  pip: 
    name: couchdb
    
- name: install textblob
  pip:
    name: textblob

- name: add repo for couchdb
  sudo: yes
  shell: "echo deb https://apache.bintray.com/couchdb-deb bionic main > /etc/apt/sources.list"

- name: import couch repo key
  sudo: yes
  apt_key:
    url: https://couchdb.apache.org/repo/bintray-pubkey.asc
    state: present

- name: update packages
  apt: update_cache=yes

- name: Select couchdb mode
  debconf:
    name: couchdb
    question: couchdb/mode
    value: clustered
    vtype: select

- name: Set couch nodename
  debconf:
    name: couchdb
    question: couchdb/nodename
    value: couchdb@{{ ansible_eth0.ipv4.address }}
    vtype: string

- name: Set couch cookie
  debconf:
    name: couchdb
    question: couchdb/cookie
    value: couchdb_cluster
    vtype: string

- name: bind couch address
  debconf:
    name: couchdb
    question: couchdb/bindaddress
    value: 0.0.0.0
    vtype: string

- name: Set couch admin password
  debconf:
    name: couchdb
    question: couchdb/adminpass
    value: "{{ COUCHDB_PASSWORD }}"
    vtype: password

- name: Set couch admin password again 
  debconf:
    name: couchdb
    question: couchdb/adminpass_again
    value: "{{ COUCHDB_PASSWORD }}"
    vtype: password


- name: couchdb seen
  debconf:
    name: couchdb
    question: couchdb/{{ item }}
    value: 'true'
    vtype: seen
  loop:
    - mode
    - nodename
    - cookie
    - bindaddress
    - adminpass
    - adminpass_again

- name: install couch
  shell: DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --force-yes couchdb

- name: change database_dir to volume storage mount point
  lineinfile: 
    dest: /opt/couchdb/etc/local.ini
    line: 'database_dir=/mydir'

- name: change port range to the ones opened in the couchdb security group 
  lineinfile: 
    dest: /opt/couchdb/etc/vm.args
    line: "{{ item }}"
  with_items:
    - '-kernel inet_dist_listen_min 9100'
    - '-kernel inet_dist_listen_max 9200'

- name: Restart service couchdb, in all cases
  service:
    name: couchdb
    state: restarted

- name: close internal firewall
  service: 
    name: ufw
    enabled: no
    state: stopped

 