---
#Role whiuch runs on the selected master node for couchdb, connecting and joining the cluster.

- name: enable cluster
  uri: status_code=201,409 HEADER_Content-Type="application/json" user=admin password=admin method=POST force_basic_auth=yes body_format=json url=http://admin:admin@{{ hostvars[groups['couchadmin'][0]].ansible_host }}:5984/_cluster_setup body='{"action":"enable_cluster","bind_address":"0.0.0.0","username":"admin","password":"admin","port":5984,"remote_node":"{{ item }}","remote_current_user":"admin","remote_current_password":"admin"}'
  loop:
    - "{{ hostvars[groups['couchnode'][0]].ansible_host }}"
    - "{{ hostvars[groups['couchnode'][1]].ansible_host }}"



- name: add nodes to the cluster
  uri: status_code=201,409 HEADER_Content-Type="application/json" user=admin password=admin method=POST force_basic_auth=yes body_format=json url=http://admin:admin@{{ hostvars[groups['couchadmin'][0]].ansible_host }}:5984/_cluster_setup body='{"action":"add_node","username":"admin","password":"admin","host":"{{ item }}","port":5984}'
  loop:
    - "{{ hostvars[groups['couchnode'][0]].ansible_host }}"
    - "{{ hostvars[groups['couchnode'][1]].ansible_host }}"


- name: finish the cluster
  uri: status_code=201 HEADER_Content-Type="application/json" user=admin password=admin method=POST force_basic_auth=yes url=http://admin:admin@{{ hostvars[groups['couchadmin'][0]].ansible_host }}:5984/_cluster_setup body_format=json body='{"action":"finish_cluster"}'